#!/bin/bash

ssh des01.kask 'echo "01" && docker exec hpcVirtualizationNode01 apk add --update nethogs'
ssh des04.kask 'echo "02" && docker exec hpcVirtualizationNode02 apk add --update nethogs'
ssh des05.kask 'echo "03" && docker exec hpcVirtualizationNode03 apk add --update nethogs'
ssh des08.kask 'echo "04" && docker exec hpcVirtualizationNode04 apk add --update nethogs'
ssh des09.kask 'echo "05" && docker exec hpcVirtualizationNode05 apk add --update nethogs'
ssh des10.kask 'echo "06" && docker exec hpcVirtualizationNode06 apk add --update nethogs'
ssh des11.kask 'echo "07" && docker exec hpcVirtualizationNode07 apk add --update nethogs'
ssh des12.kask 'echo "08" && docker exec hpcVirtualizationNode08 apk add --update nethogs'
ssh des13.kask 'echo "09" && docker exec hpcVirtualizationNode09 apk add --update nethogs'
ssh des14.kask 'echo "10" && docker exec hpcVirtualizationNode10 apk add --update nethogs'
ssh des15.kask 'echo "11" && docker exec hpcVirtualizationNode11 apk add --update nethogs'
ssh des16.kask 'echo "12" && docker exec hpcVirtualizationNode12 apk add --update nethogs'
ssh des18.kask 'echo "13" && docker exec hpcVirtualizationNode13 apk add --update nethogs'
ssh des02.kask 'echo "14" && docker exec hpcVirtualizationNode14 apk add --update nethogs'
ssh des07.kask 'echo "15" && docker exec hpcVirtualizationNode15 apk add --update nethogs'
ssh des17.kask 'echo "16" && docker exec hpcVirtualizationNode16 apk add --update nethogs'
ssh des06.kask 'echo "17" && docker exec hpcVirtualizationNode17 apk add --update nethogs'
ssh des03.kask 'echo "18" && docker exec hpcVirtualizationNode18 apk add --update nethogs'
