#!/bin/bash

ssh des01.kask 'echo "01" && docker container stop hpcVirtualizationNode01 && docker container rm hpcVirtualizationNode01'
ssh des02.kask 'echo "02" && docker container stop hpcVirtualizationNode02 && docker container rm hpcVirtualizationNode02'
ssh des03.kask 'echo "03" && docker container stop hpcVirtualizationNode03 && docker container rm hpcVirtualizationNode03'
ssh des04.kask 'echo "04" && docker container stop hpcVirtualizationNode04 && docker container rm hpcVirtualizationNode04'
ssh des05.kask 'echo "05" && docker container stop hpcVirtualizationNode05 && docker container rm hpcVirtualizationNode05'
ssh des06.kask 'echo "06" && docker container stop hpcVirtualizationNode06 && docker container rm hpcVirtualizationNode06'
ssh des07.kask 'echo "07" && docker container stop hpcVirtualizationNode07 && docker container rm hpcVirtualizationNode07'
ssh des08.kask 'echo "08" && docker container stop hpcVirtualizationNode08 && docker container rm hpcVirtualizationNode08'
ssh des09.kask 'echo "09" && docker container stop hpcVirtualizationNode09 && docker container rm hpcVirtualizationNode09'
ssh des10.kask 'echo "10" && docker container stop hpcVirtualizationNode10 && docker container rm hpcVirtualizationNode10'
ssh des11.kask 'echo "11" && docker container stop hpcVirtualizationNode11 && docker container rm hpcVirtualizationNode11'
ssh des12.kask 'echo "12" && docker container stop hpcVirtualizationNode12 && docker container rm hpcVirtualizationNode12'
ssh des13.kask 'echo "13" && docker container stop hpcVirtualizationNode13 && docker container rm hpcVirtualizationNode13'
ssh des14.kask 'echo "14" && docker container stop hpcVirtualizationNode14 && docker container rm hpcVirtualizationNode14'
ssh des15.kask 'echo "15" && docker container stop hpcVirtualizationNode15 && docker container rm hpcVirtualizationNode15'
ssh des16.kask 'echo "16" && docker container stop hpcVirtualizationNode16 && docker container rm hpcVirtualizationNode16'
ssh des17.kask 'echo "17" && docker container stop hpcVirtualizationNode17 && docker container rm hpcVirtualizationNode17'
ssh des18.kask 'echo "18" && docker container stop hpcVirtualizationNode18 && docker container rm hpcVirtualizationNode18'