#!/bin/bash

ssh des01.kask 'echo "01" && docker container start hpcVirtualizationNode01'
ssh des04.kask 'echo "02" && docker container start hpcVirtualizationNode02'
ssh des06.kask 'echo "03" && docker container start hpcVirtualizationNode03'
ssh des08.kask 'echo "04" && docker container start hpcVirtualizationNode04'
ssh des09.kask 'echo "05" && docker container start hpcVirtualizationNode05'
ssh des10.kask 'echo "06" && docker container start hpcVirtualizationNode06'
ssh des11.kask 'echo "07" && docker container start hpcVirtualizationNode07'
ssh des12.kask 'echo "08" && docker container start hpcVirtualizationNode08'
ssh des13.kask 'echo "09" && docker container start hpcVirtualizationNode09'
ssh des14.kask 'echo "10" && docker container start hpcVirtualizationNode10'
ssh des15.kask 'echo "11" && docker container start hpcVirtualizationNode11'
ssh des16.kask 'echo "12" && docker container start hpcVirtualizationNode12'
ssh des18.kask 'echo "13" && docker container start hpcVirtualizationNode13'
ssh des02.kask 'echo "14" && docker container start hpcVirtualizationNode14'
ssh des07.kask 'echo "15" && docker container start hpcVirtualizationNode15'
ssh des17.kask 'echo "16" && docker container start hpcVirtualizationNode16'
ssh des03.kask 'echo "17" && docker container start hpcVirtualizationNode17'
ssh des05.kask 'echo "18" && docker container start hpcVirtualizationNode18'
