#!/bin/bash

ssh des01.kask 'echo "01" && docker container ls'
ssh des02.kask 'echo "02" && docker container ls'
ssh des03.kask 'echo "03" && docker container ls'
ssh des04.kask 'echo "04" && docker container ls'
ssh des05.kask 'echo "05" && docker container ls'
ssh des06.kask 'echo "06" && docker container ls'
ssh des07.kask 'echo "07" && docker container ls'
ssh des08.kask 'echo "08" && docker container ls'
ssh des09.kask 'echo "09" && docker container ls'
ssh des10.kask 'echo "10" && docker container ls'
ssh des11.kask 'echo "11" && docker container ls'
ssh des12.kask 'echo "12" && docker container ls'
ssh des13.kask 'echo "13" && docker container ls'
ssh des14.kask 'echo "14" && docker container ls'
ssh des15.kask 'echo "15" && docker container ls'
ssh des16.kask 'echo "16" && docker container ls'
ssh des17.kask 'echo "17" && docker container ls'
ssh des18.kask 'echo "18" && docker container ls'
